name: CI/CD

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  bump:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        PRERELEASE: false
    - name: Save version to file
      run: echo "${{ steps.github_tag.outputs.new_tag }}" > version.txt
      id: save_version
  ci:
    needs: bump
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: install dependencies
          run: |
            npm install
          working-directory: ./

        - name: Run tests
          run: |
            npm run test
          working-directory: ./

  cd:
    needs: ci
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Login to docker
          uses: docker/login-action@v3
          with:
            username: ${{secrets.DOCKER_USER_NAME}}  
            password: ${{secrets.DOCKERHUB_TOKEN}}
        
        - name: Read version from file
          id: read_version
          run: |
            VERSION=$(cat version.txt)
            echo "::set-output name=VERSION::$VERSION"

        - name: Build and push
          run: | 
            docker build -t ${{secrets.DOCKER_USER_NAME}}/next-cicd:${{ steps.read_version.outputs.VERSION }} .
            docker push ${{secrets.DOCKER_USER_NAME}}/next-cicd:${{ steps.read_version.outputs.VERSION }}