name: CI/CD

on:
    push:
        branches:
            - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: install dependencies
          run: |
            npm install
          working-directory: ./

        - name: Run tests
          run: |
            npm run test
          working-directory: ./

  cd:
    needs: ci
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Login to docker
          uses: docker/login-action@v3
          with:
            username: ${{secrets.DOCKER_USER_NAME}}  
            password: ${{secrets.DOCKERHUB_TOKEN}}
        
        - name: Build and push
          run: | 
            docker build -t ${{secrets.DOCKER_USER_NAME}}/next-cicd
            docker push ${{secrets.DOCKER_USER_NAME}}/next-cicd