name: Check

on:
  pull_request:

jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: install dependencies
          run: |
            npm install
            exit 1
          working-directory: ./

        - name: Run tests
          run: |
            npm run test
          working-directory: ./